#include "pulp.h"
#include "const.h"

#include <Windows.h>
#include <process.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <math.h>
#include <ctype.h>

// =============================
// Config
// =============================

// The number of producer threads to spawn. Each thread will generate LOGS_PER_PRODUCER logs.
// It's better to use a number of producers (PULP thread pool caller) that is equal to the number of CPU cores available on the machine for optimal performance.
// Realistically, the number of producers should be between 1 and 8 for most machines and use cases. 1 unique thread already yields a very high throughput (>1 millions logs/s). 
// PULP is designed to handle multiple threads efficiently, but too many threads can lead to contention and reduced performance.
#define NUM_PRODUCERS        1

// The total number of logs to be produced divided by the number of producer thread. Each thread will generate this many logs. 
// The total number of logs generated by all threads will be NUM_PRODUCERS * LOGS_PER_PRODUCER.
#define LOGS_PER_PRODUCER   (250000000/NUM_PRODUCERS)

// The total number of logs generated by all producer threads.
#define TOTAL_LOGS          ((uint64_t)NUM_PRODUCERS * LOGS_PER_PRODUCER)

// =============================
// From disk
// =============================
static char** disk_urls = NULL;
static size_t disk_urls_count = 0;
static char* disk_blob_urls = NULL;

static char** disk_endpoints = NULL;
static size_t disk_endpoints_count = 0;
static char* disk_blob_endpoints = NULL;

// =============================
// Utils
// =============================
static inline uint64_t high_res_timestamp(void) {
    FILETIME ft;
    GetSystemTimePreciseAsFileTime(&ft);
    ULARGE_INTEGER uli;
    uli.LowPart = ft.dwLowDateTime;
    uli.HighPart = ft.dwHighDateTime;
    return uli.QuadPart / 10; // microsecondes
}


// RNG (PCG32 minimal, thread-local seed)
typedef struct {
    uint64_t state;
    uint64_t inc;
} pcg32_random_t;

static inline uint32_t pcg32_random_r(pcg32_random_t* rng) {
    uint64_t oldstate = rng->state;
    rng->state = oldstate * 6364136223846793005ULL + (rng->inc | 1);
    uint32_t xorshifted = (uint32_t)(((oldstate >> 18u) ^ oldstate) >> 27u);
    uint32_t rot = (uint32_t)(oldstate >> 59u);
    return (xorshifted >> rot) | (xorshifted << ((0U - rot) & 31));
}

static inline void pcg32_srandom(pcg32_random_t* rng, uint64_t initstate, uint64_t initseq) {
    rng->state = 0U;
    rng->inc = (initseq << 1u) | 1u;
    pcg32_random_r(rng);
    rng->state += initstate;
    pcg32_random_r(rng);
}


// =============================
// Entropy
// =============================
static float calculate_entropy(const char* data, size_t len) {
    uint32_t char_counts[256] = { 0 };
    for (size_t i = 0; i < len; ++i) char_counts[(uint8_t)data[i]]++;
    float entropy = 0.0f;
    for (int i = 0; i < 256; ++i)
        if (char_counts[i] > 0) {
            float p = (float)char_counts[i] / (float)len;
            entropy -= p * (float)log2(p);
        }
    return entropy;
}

// =============================
// Load from disk (shared logic)
// =============================
static int load_data_generic(const char* path, char*** lines_out, size_t* count_out, char** blob_out) {
    FILE* f = NULL;
#if defined(_MSC_VER)
    fopen_s(&f, path, "rb");
#else
    f = fopen(path, "rb");
#endif
    if (!f) { printf("Cannot open file: %s\n", path); return -1; }

    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return -1; }
    long fsz = ftell(f); if (fsz < 0) { fclose(f); return -1; }
    rewind(f);

    char* blob = (char*)malloc((size_t)fsz + 1);
    if (!blob) { fclose(f); return -1; }
    size_t rd = fread(blob, 1, (size_t)fsz, f);
    fclose(f);
    if (rd != (size_t)fsz) { free(blob); return -1; }
    blob[fsz] = '\0';

    size_t lines = 0;
    for (size_t i = 0; i < (size_t)fsz; i++)
        if (blob[i] == '\n') lines++;
    if (lines == 0) lines = 1;

    char** table = (char**)malloc(lines * sizeof(char*));
    if (!table) { free(blob); return -1; }

    size_t idx = 0;
    char* start = blob;
    for (size_t i = 0; i <= (size_t)fsz; i++) {
        if (blob[i] == '\n' || blob[i] == '\0') {
            blob[i] = '\0';
            char* line = start;
            size_t len = strlen(line);
            while (len > 0 && isspace((unsigned char)line[len - 1])) line[--len] = '\0';
            while (*line && isspace((unsigned char)*line)) ++line;
            if (len >= 2 && line[0] == '"' && line[len - 1] == '"') { line[len - 1] = '\0'; ++line; }
            len = strlen(line);
            if (len > 0 && line[len - 1] == ',') line[len - 1] = '\0';
            if (*line) table[idx++] = line;
            start = &blob[i + 1];
        }
    }

    *lines_out = table;
    *count_out = idx;
    *blob_out = blob;

    return 0;
}

static void free_data(void) {
    if (disk_urls) { free(disk_urls); disk_urls = NULL; }
    if (disk_endpoints) { free(disk_endpoints); disk_endpoints = NULL; }
    if (disk_blob_urls) { free(disk_blob_urls); disk_blob_urls = NULL; }
    if (disk_blob_endpoints) { free(disk_blob_endpoints); disk_blob_endpoints = NULL; }
    disk_urls_count = 0;
    disk_endpoints_count = 0;
}

// =============================
// API : Live Telemetry call
// =============================
static unsigned __stdcall stats_thread(void* param) {
    for (;;) {
		// The dedicated stats thread will sleep for 15 seconds before retrieving the latest stats from the PULP. 
		// This interval is chosen to balance between getting timely statistics and not overloading the system with frequent calls (it can be called more frequently if needed, but 15 seconds is a good starting point).
		// The PulpGetStats() function is not thread-safe and block the PULP execution for a few milliseconds, for sampling the throughput.
        Sleep(15000);
        char* s = PulpGetStats();
        printf("JSON Stats : %s\n", s);
        PulpFreeStats(s);
    }
}

// =============================
// Log Producer Thread
// =============================
static unsigned __stdcall producer_thread(void* param) {
    pcg32_random_t rng;
    pcg32_srandom(&rng, high_res_timestamp(), GetCurrentThreadId());

    char urlbuf[700] = { 0 };
    char ipbuf[80] = { 0 };

    for (uint32_t i = 0; i < LOGS_PER_PRODUCER; i++) {
        size_t url_idx = pcg32_random_r(&rng) % disk_urls_count;
        size_t ip_idx = pcg32_random_r(&rng) % disk_endpoints_count;
        size_t code_idx = pcg32_random_r(&rng) % _countof(codes);
        size_t method_idx = pcg32_random_r(&rng) % _countof(methods);
        uint64_t timestamp = high_res_timestamp();

        // =============================
        // API : PulpWrite call
        // =============================
        int rtn = PulpWrite((uint8_t)method_idx,
            disk_urls[url_idx], (uint32_t)strlen(disk_urls[url_idx]),
            codes[code_idx], disk_endpoints[ip_idx], (uint32_t)strlen(disk_endpoints[ip_idx]),
            (uint16_t)(pcg32_random_r(&rng) % UINT16_MAX),
            (uint16_t)(pcg32_random_r(&rng) % UINT16_MAX),
            (uint8_t)(pcg32_random_r(&rng) % UINT8_MAX),
            timestamp);
        if (rtn != 0) printf("PulpWrite rtn value : %d\n", rtn);
    }

    return 0;
}

// =============================
// Main
// =============================
int main(void) {

    // Test datasets
    // Resources
    if (load_data_generic("C:\\dataset\\resource_mixed_1M300K.txt",
        &disk_urls, &disk_urls_count, &disk_blob_urls) == 0) {
        printf("Loaded %zu URLs\n", disk_urls_count);
    }
    // Resource : Shannon entropy level of the dataset for this benchmark (measured in bits per byte, max = 8.0).
	// Higher entropy indicates more random data, making compression harder. Longer strings, cardinality, influence performance and compression ratio. The following are some reference entropy levels for different datasets:
	// - 3.61 bits/byte: resource_simple_urls.txt is a realistic baseline, representative of real-world structured HTTP logs with limited cardinality (1100 short urls).
    // - 4.37 bits/byte: resource_mixed_1M300K.txt is a medium-high entropy workload designed to stress compression efficiency with very high cardinality (1347695 filepaths and urls)
	// - 3.96 bits/byte: resource_urls_wParams.txt is a high cardinality workload (235370 valid urls entries, some with params).
    float avg_entropy = 0.0f;
    for (int i = 0; i < disk_urls_count; i++)
        avg_entropy += calculate_entropy(disk_urls[i], strlen(disk_urls[i]));
    avg_entropy /= (float)disk_urls_count;
    printf("Resources list entropy : %.2f\n", avg_entropy);


    // Endpoints
    if (load_data_generic("C:\\dataset\\endpoints_complex.txt",
        &disk_endpoints, &disk_endpoints_count, &disk_blob_endpoints) == 0) {
        printf("Loaded %zu endpoints\n", disk_endpoints_count);
    }
    // Endpoints : Shannon entropy level of the dataset for this benchmark (measured in bits per byte, max = 8.0).
    // Higher entropy indicates more random data, making compression harder. Longer strings, cardinality, influence performance and compression ratio. The following are some reference entropy levels for different datasets:
    // - 2.48 bits/byte: endpoints_ipv4.txt is a realistic baseline, representative of real-world ipv4 set with limited cardinality (5096 ipv4).
    // - 3.71 bits/byte: endpoints_ipv6.txt is a medium-high entropy workload designed to stress compression efficiency with very high cardinality (50000 ipv6)
    // - 4.45 bits/byte: endpoints_complex.txt is a high entropy workload (10000 custom 'mmo like' endpoints).
    avg_entropy = 0.0f;
    for (int i = 0; i < (int)disk_endpoints_count; i++)
        avg_entropy += calculate_entropy(disk_endpoints[i], strlen(disk_endpoints[i]));
    avg_entropy /= (float)disk_endpoints_count;
    printf("Endpoints list entropy : %.2f\n", avg_entropy);

    // =============================
    // API : PulpInit call
    // =============================
    uint8_t rtn = PulpInit(
        "C:\\logs",                // Log Path
        "C:\\AltLogspath",         // Hot Swap backup (if main path fails)
        "C:\\logs\\error",         // Error file path
        1,                         // Inter-thread atomic numeration (1 == ON, 0 == OFF)
        ANON_IP_NONE,              // IP Anon
        0,                         // Truncate params on resource field (1 == ON, 0 == OFF)
		1024,                       // Batches per file before rotation (must be power of two, default 512)
        COMPRESSION_BALANCED,      // Compression level
        BATCH_500KB,               // Batch size
        DICT_16K                   // Dictionnary size (nb entries)
    );
    printf("LogInit status : %d %s\n", rtn, rtn == 0 ? "OK" : rtn == 17 ? "WARN" : "FAILED");
    if (rtn != 0) return 0;

    HANDLE producers[NUM_PRODUCERS] = { 0 };
    HANDLE stats = 0;

    LARGE_INTEGER _t0, _t1, _freq;
    QueryPerformanceFrequency(&_freq);
    QueryPerformanceCounter(&_t0);

    for (int i = 0; i < NUM_PRODUCERS; i++)
        producers[i] = (HANDLE)_beginthreadex(NULL, 0, producer_thread, NULL, 0, NULL);
    stats = (HANDLE)_beginthreadex(NULL, 0, stats_thread, NULL, 0, NULL);

    WaitForMultipleObjects(NUM_PRODUCERS, producers, TRUE, INFINITE);

    QueryPerformanceCounter(&_t1);

    // =============================
    // API : PulpShutdown call
    // =============================
    PulpShutdown();

    double elapsed = (double)(_t1.QuadPart - _t0.QuadPart) / (double)_freq.QuadPart;
    printf("Total logs: %llu\n", (unsigned long long)TOTAL_LOGS);
    printf("Time: %.2f seconds\n", elapsed);
    printf("Throughput: %.2f million logs/s\n", TOTAL_LOGS / elapsed / 1000000.0);

    for (int i = 0; i < NUM_PRODUCERS; i++)
        if (producers[i] && producers[i] != INVALID_HANDLE_VALUE)
            CloseHandle(producers[i]);
    CloseHandle(stats);

    free_data();

    return 0;
}
